# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000020000000000000015"
    chainName: celestiatestnet
    connections:
      - token: cosmosnative|nobletestnet|0x726f757465725f61707000000000000000000000000000010000000000000008
      - token: ethereum|edentestnet|0xe1141469cff3db185a0e1b9ebd1d31bb22a623ea
    decimals: 6
    name: USDC
    standard: CosmosNativeHypSynthetic
    symbol: USDC
  - addressOrDenom: "0xe1141469cff3db185a0e1b9ebd1d31bb22a623ea"
    chainName: edentestnet
    connections:
      - token: cosmosnative|celestiatestnet|0x726f757465725f61707000000000000000000000000000020000000000000015
    decimals: 6
    name: USDC
    standard: EvmHypSynthetic
    symbol: USDC
  - addressOrDenom: "0x726f757465725f61707000000000000000000000000000010000000000000008"
    chainName: nobletestnet
    connections:
      - token: cosmosnative|celestiatestnet|0x726f757465725f61707000000000000000000000000000020000000000000015
    decimals: 6
    name: USDC
    standard: CosmosNativeHypCollateral
    symbol: USDC
